# Generated by Django 5.0.6 on 2024-05-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banner/%Y/%m/%d/'),
        ),
    ]
