# Generated by Django 5.0.6 on 2024-05-15 12:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_app', '0002_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('content', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('slug', models.CharField(default=uuid.uuid4, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_header', models.CharField(blank=True, max_length=250, null=True)),
                ('blog_title', models.CharField(blank=True, max_length=250, null=True)),
                ('blog_video', models.FileField(blank=True, null=True, upload_to='Blog/')),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='Blog/%Y/%m/%d/')),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('slug', models.CharField(default=uuid.uuid4, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.CharField(blank=True, max_length=250, null=True)),
                ('projects', models.CharField(blank=True, max_length=250, null=True)),
                ('hours_Of_Support', models.CharField(blank=True, max_length=250, null=True)),
                ('workers', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('slug', models.CharField(default=uuid.uuid4, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('subject', models.CharField(blank=True, max_length=250, null=True)),
                ('message', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tollfree1', models.CharField(blank=True, max_length=250, null=True)),
                ('tollfree2', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('servicehours', models.TextField(blank=True, null=True)),
                ('iphonelink', models.CharField(blank=True, max_length=250, null=True)),
                ('androidlink', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('slug', models.CharField(default=uuid.uuid4, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_type', models.CharField(blank=True, max_length=250, null=True)),
                ('question', models.CharField(blank=True, max_length=250, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('slug', models.CharField(default=uuid.uuid4, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('global_image', models.ImageField(blank=True, null=True, upload_to='globalsetting/%Y/%m/%d/')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='globalsetting/%Y/%m/%d/')),
                ('global_url_insta', models.URLField(blank=True, null=True)),
                ('global_url_facebook', models.URLField(blank=True, null=True)),
                ('global_url_twitter', models.URLField(blank=True, null=True)),
                ('insta_is_active', models.BooleanField(default=True)),
                ('facebook_is_active', models.BooleanField(default=True)),
                ('twitter_is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('slug', models.CharField(default=uuid.uuid4, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/%Y/%m/%d/')),
                ('content', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('slug', models.CharField(default=uuid.uuid4, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('content', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('slug', models.CharField(default=uuid.uuid4, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('designation', models.CharField(blank=True, max_length=250, null=True)),
                ('detail', models.CharField(blank=True, max_length=250, null=True)),
                ('twitter', models.CharField(blank=True, max_length=250, null=True)),
                ('facebook', models.CharField(blank=True, max_length=250, null=True)),
                ('instagram', models.CharField(blank=True, max_length=250, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('slug', models.CharField(default=uuid.uuid4, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('desgination', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('testimonial_image', models.ImageField(blank=True, null=True, upload_to='testimonial/%Y/%m/%d/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('slug', models.CharField(default=uuid.uuid4, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='workwith/%Y/%m/%d/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('slug', models.CharField(default=uuid.uuid4, max_length=250, unique=True)),
            ],
        ),
    ]
