# Generated by Django 5.0.6 on 2024-05-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_app', '0003_about_blog_companystatus_contactus_customerservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team/%Y/%m/%d/'),
        ),
    ]
