# Generated by Django 5.0.6 on 2024-05-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_app', '0004_team_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
