# Generated by Django 5.0.6 on 2024-05-24 11:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_app', '0006_banner_created_at_contactus_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='meta_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
