# Generated by Django 5.0.6 on 2024-05-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_app', '0007_alter_blog_meta_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.TextField(blank=True, max_length=250, null=True)),
                ('portfolio', models.TextField(blank=True, max_length=250, null=True)),
                ('team', models.TextField(blank=True, max_length=250, null=True)),
                ('call_to_action', models.TextField(blank=True, max_length=250, null=True)),
                ('testimonials', models.TextField(blank=True, max_length=250, null=True)),
                ('recent_posts', models.TextField(blank=True, max_length=250, null=True)),
                ('contact', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
