# Generated by Django 5.0.6 on 2024-05-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_app', '0008_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='faq',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
