# Generated by Django 5.0.6 on 2024-05-25 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_app', '0009_heading_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='visitor',
            field=models.IntegerField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='BlogVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_user', models.CharField(blank=True, max_length=250, null=True)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='static_app.blog')),
            ],
        ),
    ]
