# Generated by Django 5.0.6 on 2024-05-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_app', '0010_blog_visitor_blogvisitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='visitor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
