# Generated by Django 5.0.6 on 2024-05-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_app', '0011_alter_blog_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
