# Generated by Django 5.0.6 on 2024-07-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_app', '0013_alter_about_content_alter_services_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='clients/%Y/%m/%d/')),
            ],
        ),
    ]
