# Generated by Django 5.0.4 on 2024-08-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_app', '0014_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='global_url_linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='linkedin_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
